log-level = "TRACE"
relay = true
mix = true
filter = true
store = true
lightpush = true
max-connections = 150
peer-exchange = false
metrics-logging = false
cluster-id = 2
discv5-discovery = false
discv5-udp-port = 9000
discv5-enr-auto-update = true
enable-kad-discovery = true
rest = true
rest-admin = true
ports-shift = 1
num-shards-in-network = 1
shard = [0]
agent-string = "nwaku-mix"
nodekey = "f98e3fba96c32e8d1967d460f1b79457380e1a895f7971cecc8528abe733781a"
mixkey = "a87db88246ec0eedda347b9b643864bee3d6933eb15ba41e6d58cb678d813258"
rendezvous = false
listen-address = "127.0.0.1"
nat = "extip:127.0.0.1"
ext-multiaddr = ["/ip4/127.0.0.1/tcp/60001"]
ext-multiaddr-only = true
ip-colocation-limit=0
